name: Executa Testes Unitários

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Configurar ambiente
      uses: actions/setup-java@v3.13.0
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven

    - name: Executar Testes
      run: |
        # Executar testes unitários do Spring.
        mvn test -Dspring.profiles.active=test

    - name: Comment on PR
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const result = 'Testes passaram com sucesso!';  # Mensagem de sucesso
          if (process.env.GITHUB_ACTIONS === 'true') {
            const prNumber = context.payload.pull_request.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            github.issues.createComment({
              owner: owner,
              repo: repo,
              issue_number: prNumber,
              body: result
            });
          } else {
            console.log('Ação executada localmente. Comentário não adicionado.');
          }
